import { createFileRoute } from "@tanstack/react-router";
import { Sparkles, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { TREND } from "@/lib/demo-data";
import { formatKES } from "@/lib/format";

export const Route = createFileRoute("/app/ai-insights")({
  head: () => ({ meta: [{ title: "AI Insights — Kim-Fay OrderWatch" }] }),
  component: InsightsPage,
});

const chartAxis = { stroke: "var(--color-muted-foreground)", fontSize: 11 } as const;

const SECTIONS = [
  {
    id: "executive",
    label: "Executive Summary",
    bullets: [
      "Order capture today is 98.4%, ahead of the 98% target.",
      "Revenue at risk stands at KES 4.2M, concentrated in 12 POs from Carrefour and Naivas.",
      "Average processing time improved 18% week-over-week to 1h 42m.",
      "Critical orders >1M increased from 4 to 7 — driven by month-end Carrefour replenishment.",
    ],
  },
  {
    id: "operational",
    label: "Operational Summary",
    bullets: [
      "Outlook ingested 142 order emails since 06:00; 138 had PO numbers extracted (97.2% confidence avg).",
      "Acumatica hourly sync returned 412 sales orders; 4 mismatches flagged.",
      "Top blocking reason: 'PO not yet in Acumatica' (62% of outstanding).",
      "SLA breaches concentrated in Chandarana (8h target) — 3 of 5 breaches.",
    ],
  },
  {
    id: "revenue",
    label: "Revenue Risk Analysis",
    bullets: [
      "Critical band (>KES 1M) accounts for 71% of at-risk revenue from only 14% of order count.",
      "Carrefour represents 38% of revenue at risk — single largest concentration.",
      "Predicted recovery within SLA window: KES 3.1M (74%).",
      "Forecast end-of-day revenue at risk: KES 2.8M assuming current capture velocity holds.",
    ],
  },
  {
    id: "root-cause",
    label: "Root Cause Analysis",
    bullets: [
      "12 Naivas emails failed PO extraction due to 'Re: Re:' subject prefixes — rule update recommended.",
      "Acumatica 15:00 sync returned zero new orders 3 days running; likely connector timeout.",
      "Quickmart sender address changed last Tuesday; 4 orders routed to spam before whitelist updated.",
      "Chandarana SLA target of 8h is too tight for orders received after 16:00 — recommend 12h after-hours bucket.",
    ],
  },
  {
    id: "cs",
    label: "CS Performance",
    bullets: [
      "Wanjiru K. resolves Carrefour discrepancies 2.1× faster than team average.",
      "Average agent queue depth: 14 (target <20). Otieno M. peaked at 28 yesterday.",
      "First-touch resolution: 71% (last 7 days, +6 pts w/w).",
      "Escalation rate: 4.2% — slightly above 4% target. Driven by Carrefour high-value queue.",
    ],
  },
  {
    id: "recommendations",
    label: "Recommendations",
    bullets: [
      "Reassign 3 active Carrefour POs from Otieno M. to Wanjiru K. — protects KES 2.4M.",
      "Update Naivas subject pattern to allow up to 3 'Re:' prefixes.",
      "Investigate and restart the 15:00 Acumatica scheduled job.",
      "Add a 'Critical >1M' fast-lane in the Discrepancies board with manager auto-assign.",
    ],
  },
  {
    id: "trend",
    label: "Trend Analysis",
    bullets: [
      "Capture rate trending up 1.4 pts over 14 days.",
      "Revenue at risk peaks mid-week (Tue/Wed) and on month-end days.",
      "SLA breaches dropped 22% week-over-week after Quickmart sender fix.",
      "AOV trending up 8.3% — driven by Carrefour bulk orders growth.",
    ],
  },
] as const;

function InsightsPage() {
  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-end justify-between gap-2">
        <div>
          <h1 className="flex items-center gap-2 text-xl font-semibold tracking-tight">
            <Sparkles className="h-5 w-5 text-primary" /> AI Insights
          </h1>
          <p className="text-sm text-muted-foreground">
            Generated by OpenAI every 3 hours — last run 12:00, next run 15:00.
          </p>
        </div>
        <Button size="sm" variant="outline" onClick={() => toast.success("Manual insight run queued")}>
          <RefreshCw className="mr-1 h-3.5 w-3.5" /> Regenerate now
        </Button>
      </div>

      <Tabs defaultValue="executive" className="space-y-4">
        <TabsList className="flex h-auto flex-wrap gap-1 bg-muted/40 p-1">
          {SECTIONS.map((s) => (
            <TabsTrigger key={s.id} value={s.id} className="text-xs">{s.label}</TabsTrigger>
          ))}
        </TabsList>

        {SECTIONS.map((s) => (
          <TabsContent key={s.id} value={s.id} className="space-y-3">
            <div className="rounded-lg border bg-card p-5 shadow-[var(--shadow-panel)]">
              <div className="mb-3 flex items-center justify-between">
                <h3 className="text-sm font-semibold">{s.label}</h3>
                <span className="text-[11px] text-muted-foreground">12:00 cycle · GPT analysis</span>
              </div>
              <ul className="space-y-2.5">
                {s.bullets.map((b, i) => (
                  <li key={i} className="flex gap-2 text-sm leading-relaxed">
                    <span className="mt-1.5 inline-block h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                    <span>{b}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="grid gap-3 md:grid-cols-2">
              <div className="rounded-lg border bg-card p-4 shadow-[var(--shadow-panel)]">
                <h4 className="mb-2 text-sm font-semibold">Supporting Trend — Capture %</h4>
                <div className="h-40">
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={TREND}>
                      <CartesianGrid stroke="var(--color-border)" strokeDasharray="3 3" vertical={false} />
                      <XAxis dataKey="date" {...chartAxis} />
                      <YAxis {...chartAxis} domain={[80, 100]} />
                      <Tooltip />
                      <Line type="monotone" dataKey="captureRate" stroke="var(--color-chart-2)" strokeWidth={2} dot={false} />
                    </LineChart>
                  </ResponsiveContainer>
                </div>
              </div>
              <div className="rounded-lg border bg-card p-4 shadow-[var(--shadow-panel)]">
                <h4 className="mb-2 text-sm font-semibold">Supporting Trend — Revenue</h4>
                <div className="h-40">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={TREND}>
                      <CartesianGrid stroke="var(--color-border)" strokeDasharray="3 3" vertical={false} />
                      <XAxis dataKey="date" {...chartAxis} />
                      <YAxis {...chartAxis} tickFormatter={(v) => `${(v / 1_000_000).toFixed(1)}M`} />
                      <Tooltip formatter={(v: number) => formatKES(v, { compact: true })} />
                      <Bar dataKey="revenue" fill="var(--color-chart-1)" radius={[3, 3, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </div>
            </div>
          </TabsContent>
        ))}
      </Tabs>
    </div>
  );
}
