<?php
namespace Tests\Feature;
use App\Models\AcumaticaSalesOrder;
use App\Models\FulfillmentHistorySnapshot;
use App\Services\Operations\FulfillmentHistoryService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
class FulfillmentHistoryTest extends TestCase {
 use RefreshDatabase;
 public function test_first_completed_snapshot_is_immutable_and_uses_open_times_unit_price():void{$order=AcumaticaSalesOrder::create(['acumatica_order_nbr'=>'SO-HIST','order_type'=>'SO','status'=>'Completed','order_date'=>'2026-06-22','customer_acumatica_id'=>'C1']);$service=app(FulfillmentHistoryService::class);$first=$service->captureFirstCompleted($order,['Details'=>[['LineNbr'=>['value'=>1],'InventoryID'=>['value'=>'SKU1'],'OrderQty'=>['value'=>150],'QtyOnShipments'=>['value'=>144],'OpenQty'=>['value'=>6],'UnitPrice'=>['value'=>1900]]]],'test',1);$second=$service->captureFirstCompleted($order,['Details'=>[['LineNbr'=>['value'=>1],'InventoryID'=>['value'=>'SKU1'],'OrderQty'=>['value'=>150],'QtyOnShipments'=>['value'=>150],'OpenQty'=>['value'=>0],'UnitPrice'=>['value'=>1900]]]],'later',2);$this->assertSame(11400.0,(float)$first->historical_shortfall_amount);$this->assertSame($first->id,$second->id);$this->assertSame(6.0,(float)$second->lines()->first()->open_qty);$this->assertSame('test',$second->source);}
 public function test_completed_full_delivery_does_not_invent_extended_amount_backorder():void{$order=AcumaticaSalesOrder::create(['acumatica_order_nbr'=>'SO359099-X','order_type'=>'SO','status'=>'Completed','order_date'=>'2026-06-22']);$snapshot=app(FulfillmentHistoryService::class)->captureFirstCompleted($order,['Details'=>[['InventoryID'=>['value'=>'A'],'OrderQty'=>['value'=>150],'QtyOnShipments'=>['value'=>150],'OpenQty'=>['value'=>0],'UnitPrice'=>['value'=>1900],'ExtendedPrice'=>['value'=>285000]],['InventoryID'=>['value'=>'B'],'OrderQty'=>['value'=>150],'QtyOnShipments'=>['value'=>150],'OpenQty'=>['value'=>0],'UnitPrice'=>['value'=>1900],'ExtendedPrice'=>['value'=>285000]]]]);$this->assertSame(0.0,(float)$snapshot->historical_shortfall_amount);$this->assertSame(0.0,(float)$snapshot->total_missing_qty);}
 public function test_twenty_four_at_four_sixty_is_eleven_thousand_and_forty():void{$order=AcumaticaSalesOrder::create(['acumatica_order_nbr'=>'SO-11040','order_type'=>'SO','status'=>'Completed','order_date'=>'2026-06-22']);$snapshot=app(FulfillmentHistoryService::class)->captureFirstCompleted($order,['Details'=>[['InventoryID'=>['value'=>'SKU'],'OrderQty'=>['value'=>100],'QtyOnShipments'=>['value'=>76],'OpenQty'=>['value'=>24],'UnitPrice'=>['value'=>460],'ExtendedPrice'=>['value'=>570000]]]]);$this->assertSame(11040.0,(float)$snapshot->historical_shortfall_amount);$this->assertNotSame(570000.0,(float)$snapshot->historical_shortfall_amount);}
}
