/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSoImportsRouteImport } from './routes/app.so-imports'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppOrderMatchRouteImport } from './routes/app.order-match'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMailboxRouteImport } from './routes/app.mailbox'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppFillRateRouteImport } from './routes/app.fill-rate'
import { Route as AppDiscrepanciesRouteImport } from './routes/app.discrepancies'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppCustomerFeedRouteImport } from './routes/app.customer-feed'
import { Route as AppCreditNotesMoreRouteImport } from './routes/app.credit-notes-more'
import { Route as AppBackordersRouteImport } from './routes/app.backorders'
import { Route as AppAiIntelligenceRouteImport } from './routes/app.ai-intelligence'
import { Route as AppAiInsightsRouteImport } from './routes/app.ai-insights'
import { Route as AppAdministrationRouteImport } from './routes/app.administration'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSoImportsRoute = AppSoImportsRouteImport.update({
  id: '/so-imports',
  path: '/so-imports',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderMatchRoute = AppOrderMatchRouteImport.update({
  id: '/order-match',
  path: '/order-match',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMailboxRoute = AppMailboxRouteImport.update({
  id: '/mailbox',
  path: '/mailbox',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppFillRateRoute = AppFillRateRouteImport.update({
  id: '/fill-rate',
  path: '/fill-rate',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscrepanciesRoute = AppDiscrepanciesRouteImport.update({
  id: '/discrepancies',
  path: '/discrepancies',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerFeedRoute = AppCustomerFeedRouteImport.update({
  id: '/customer-feed',
  path: '/customer-feed',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditNotesMoreRoute = AppCreditNotesMoreRouteImport.update({
  id: '/credit-notes-more',
  path: '/credit-notes-more',
  getParentRoute: () => AppRoute,
} as any)
const AppBackordersRoute = AppBackordersRouteImport.update({
  id: '/backorders',
  path: '/backorders',
  getParentRoute: () => AppRoute,
} as any)
const AppAiIntelligenceRoute = AppAiIntelligenceRouteImport.update({
  id: '/ai-intelligence',
  path: '/ai-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministrationRoute = AppAdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/administration': typeof AppAdministrationRoute
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/ai-intelligence': typeof AppAiIntelligenceRoute
  '/app/backorders': typeof AppBackordersRoute
  '/app/credit-notes-more': typeof AppCreditNotesMoreRoute
  '/app/customer-feed': typeof AppCustomerFeedRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/discrepancies': typeof AppDiscrepanciesRoute
  '/app/fill-rate': typeof AppFillRateRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/mailbox': typeof AppMailboxRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/order-match': typeof AppOrderMatchRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/so-imports': typeof AppSoImportsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/administration': typeof AppAdministrationRoute
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/ai-intelligence': typeof AppAiIntelligenceRoute
  '/app/backorders': typeof AppBackordersRoute
  '/app/credit-notes-more': typeof AppCreditNotesMoreRoute
  '/app/customer-feed': typeof AppCustomerFeedRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/discrepancies': typeof AppDiscrepanciesRoute
  '/app/fill-rate': typeof AppFillRateRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/mailbox': typeof AppMailboxRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/order-match': typeof AppOrderMatchRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/so-imports': typeof AppSoImportsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/administration': typeof AppAdministrationRoute
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/ai-intelligence': typeof AppAiIntelligenceRoute
  '/app/backorders': typeof AppBackordersRoute
  '/app/credit-notes-more': typeof AppCreditNotesMoreRoute
  '/app/customer-feed': typeof AppCustomerFeedRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/discrepancies': typeof AppDiscrepanciesRoute
  '/app/fill-rate': typeof AppFillRateRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/mailbox': typeof AppMailboxRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/order-match': typeof AppOrderMatchRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/so-imports': typeof AppSoImportsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/administration'
    | '/app/ai-insights'
    | '/app/ai-intelligence'
    | '/app/backorders'
    | '/app/credit-notes-more'
    | '/app/customer-feed'
    | '/app/customers'
    | '/app/discrepancies'
    | '/app/fill-rate'
    | '/app/inventory'
    | '/app/mailbox'
    | '/app/notifications'
    | '/app/order-match'
    | '/app/orders'
    | '/app/profile'
    | '/app/reports'
    | '/app/so-imports'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/administration'
    | '/app/ai-insights'
    | '/app/ai-intelligence'
    | '/app/backorders'
    | '/app/credit-notes-more'
    | '/app/customer-feed'
    | '/app/customers'
    | '/app/discrepancies'
    | '/app/fill-rate'
    | '/app/inventory'
    | '/app/mailbox'
    | '/app/notifications'
    | '/app/order-match'
    | '/app/orders'
    | '/app/profile'
    | '/app/reports'
    | '/app/so-imports'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/administration'
    | '/app/ai-insights'
    | '/app/ai-intelligence'
    | '/app/backorders'
    | '/app/credit-notes-more'
    | '/app/customer-feed'
    | '/app/customers'
    | '/app/discrepancies'
    | '/app/fill-rate'
    | '/app/inventory'
    | '/app/mailbox'
    | '/app/notifications'
    | '/app/order-match'
    | '/app/orders'
    | '/app/profile'
    | '/app/reports'
    | '/app/so-imports'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/so-imports': {
      id: '/app/so-imports'
      path: '/so-imports'
      fullPath: '/app/so-imports'
      preLoaderRoute: typeof AppSoImportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/order-match': {
      id: '/app/order-match'
      path: '/order-match'
      fullPath: '/app/order-match'
      preLoaderRoute: typeof AppOrderMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mailbox': {
      id: '/app/mailbox'
      path: '/mailbox'
      fullPath: '/app/mailbox'
      preLoaderRoute: typeof AppMailboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fill-rate': {
      id: '/app/fill-rate'
      path: '/fill-rate'
      fullPath: '/app/fill-rate'
      preLoaderRoute: typeof AppFillRateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discrepancies': {
      id: '/app/discrepancies'
      path: '/discrepancies'
      fullPath: '/app/discrepancies'
      preLoaderRoute: typeof AppDiscrepanciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customer-feed': {
      id: '/app/customer-feed'
      path: '/customer-feed'
      fullPath: '/app/customer-feed'
      preLoaderRoute: typeof AppCustomerFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/credit-notes-more': {
      id: '/app/credit-notes-more'
      path: '/credit-notes-more'
      fullPath: '/app/credit-notes-more'
      preLoaderRoute: typeof AppCreditNotesMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/backorders': {
      id: '/app/backorders'
      path: '/backorders'
      fullPath: '/app/backorders'
      preLoaderRoute: typeof AppBackordersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-intelligence': {
      id: '/app/ai-intelligence'
      path: '/ai-intelligence'
      fullPath: '/app/ai-intelligence'
      preLoaderRoute: typeof AppAiIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-insights': {
      id: '/app/ai-insights'
      path: '/ai-insights'
      fullPath: '/app/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/administration': {
      id: '/app/administration'
      path: '/administration'
      fullPath: '/app/administration'
      preLoaderRoute: typeof AppAdministrationRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdministrationRoute: typeof AppAdministrationRoute
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppAiIntelligenceRoute: typeof AppAiIntelligenceRoute
  AppBackordersRoute: typeof AppBackordersRoute
  AppCreditNotesMoreRoute: typeof AppCreditNotesMoreRoute
  AppCustomerFeedRoute: typeof AppCustomerFeedRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDiscrepanciesRoute: typeof AppDiscrepanciesRoute
  AppFillRateRoute: typeof AppFillRateRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMailboxRoute: typeof AppMailboxRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrderMatchRoute: typeof AppOrderMatchRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSoImportsRoute: typeof AppSoImportsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdministrationRoute: AppAdministrationRoute,
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppAiIntelligenceRoute: AppAiIntelligenceRoute,
  AppBackordersRoute: AppBackordersRoute,
  AppCreditNotesMoreRoute: AppCreditNotesMoreRoute,
  AppCustomerFeedRoute: AppCustomerFeedRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDiscrepanciesRoute: AppDiscrepanciesRoute,
  AppFillRateRoute: AppFillRateRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMailboxRoute: AppMailboxRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrderMatchRoute: AppOrderMatchRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSoImportsRoute: AppSoImportsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
